{"exception":"frappe.exceptions.PermissionError: You do not have permission to view this document","exc":"[\"Traceback (most recent call last):\\n  File \\\"apps/frappe/frappe/app.py\\\", line 95, in application\\n    response = frappe.api.handle()\\n  File \\\"apps/frappe/frappe/api.py\\\", line 54, in handle\\n    return frappe.handler.handle()\\n  File \\\"apps/frappe/frappe/handler.py\\\", line 47, in handle\\n    data = execute_cmd(cmd)\\n  File \\\"apps/frappe/frappe/handler.py\\\", line 85, in execute_cmd\\n    return frappe.call(method, **frappe.form_dict)\\n  File \\\"apps/frappe/frappe/__init__.py\\\", line 1622, in call\\n    return fn(*args, **newargs)\\n  File \\\"apps/frappe/frappe/utils/print_format.py\\\", line 131, in download_pdf\\n    validate_print_permission(doc)\\n  File \\\"apps/frappe/frappe/www/printview.py\\\", line 366, in validate_print_permission\\n    raise frappe.PermissionError(_(\\\"You do not have permission to view this document\\\"))\\nfrappe.exceptions.PermissionError: You do not have permission to view this document\\n\"]"}